### ISSUE TITLE
PHPStan throws undefined static method using modal method

### ISSUE THREAD

**Issue by tcampbPPU** [lepikhinb/momentum-modal#15]
Just recently I started seeing this following phpstan/larastan issue.
```
Call to an undefined static method Inertia\Inertia::modal().
```
Which my controller looks a litttle somthing like
```php
<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Momentum\Modal\Modal as InertiaModal;

class FolderController extends Controller
{
    public function __invoke(): InertiaModal
    {
        return Inertia::modal('Folder/Create')->baseRoute('home');
    }
}
```
and my `phpstan.neon` is using the base configuraiton
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app

    level: 5

    ignoreErrors:

    excludePaths:

    checkMissingIterableValueType: false
```

Any idea's or something I must add to my `phpstan.neon`? The method works fine still, just trying to clean up stan issues.
